### ISSUE TITLE
Could you send me the compiled program?

### ISSUE THREAD

**Issue by ghost** [stag019/rgbgfx#13]
I'm sorry but I couldn't find any other way to contact you (I suck at github) I also can't get cygwin working, could you just send me the executable, I really need it :) Thanks, and sorry for posting this here.

**Comment by dannye** [comment]
You don't need cygwin to compile rgbgfx. You can just compile it like any old c code in cmd.

I'm also not sure why you need it. It's still not very feature-rich. Until then, gfx.py is sufficient.

Also, classy:
https://github.com/KairuMKDS/pokered/commit/18502e1614eeac9e2d0140fabf92d102cfbcefad

**Comment by mx86** [comment]
@dannye I don't know about anyone else but I need it because your TCG disasm says I need it.
@KairuMKDS It requires libpng less than 1.5.0, if that helps any. Since you're using cygwin, you'd want libpng12-devel. Edit the makefile to use `libpng12` instead of `libpng`, then run `make`.

**Comment by dannye** [comment]
For anyone who has trouble getting rgbgfx to work, I made a separate branch for tcg that uses gfx.py for now.
https://github.com/dannye/tcg/tree/gfx.py

Hopefully at some point, rgbgfx will become a real part of rgbds, and then the gfx.py branch will not be continued.

**Comment by stag019** [comment]
Yes. Closed now.
